// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupportDesk.Infrastructure.Data;

#nullable disable

namespace SupportDesk.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903014221_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupportDesk.Core.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Department = "Technical",
                            Email = "ermal@pecb.com",
                            FullName = "Ermal Komoni",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Department = "Billing",
                            Email = "njomza@pecb.com",
                            FullName = "Njomza PECB",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Department = "Technical",
                            Email = "pecb-test-user1@pecb.com",
                            FullName = "PECB Test User 1",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Department = "General",
                            Email = "pecb-test-user2@pecb.com",
                            FullName = "PECB Test User 2",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Department = "Technical",
                            Email = "pecb-test-user3@pecb.com",
                            FullName = "PECB Test User 3",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("SupportDesk.Core.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SupportDesk.Core.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("DueDate");

                    b.HasIndex("Priority");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Reference = "TCK-2026-0001",
                            Status = "New",
                            Title = "Sample ticket 1"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Reference = "TCK-2026-0002",
                            Status = "InProgress",
                            Title = "Sample ticket 2"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Reference = "TCK-2026-0003",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Resolved",
                            Title = "Sample ticket 3"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            ClosedDate = new DateTime(2026, 8, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Reference = "TCK-2026-0004",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Closed",
                            Title = "Sample ticket 4"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Normal",
                            Reference = "TCK-2026-0005",
                            Status = "New",
                            Title = "Sample ticket 5"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Normal",
                            Reference = "TCK-2026-0006",
                            Status = "InProgress",
                            Title = "Sample ticket 6"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Normal",
                            Reference = "TCK-2026-0007",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Resolved",
                            Title = "Sample ticket 7"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            ClosedDate = new DateTime(2026, 8, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Normal",
                            Reference = "TCK-2026-0008",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Closed",
                            Title = "Sample ticket 8"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000009"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Reference = "TCK-2026-0009",
                            Status = "New",
                            Title = "Sample ticket 9"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000010"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Reference = "TCK-2026-0010",
                            Status = "InProgress",
                            Title = "Sample ticket 10"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000011"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Reference = "TCK-2026-0011",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Resolved",
                            Title = "Sample ticket 11"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000012"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            ClosedDate = new DateTime(2026, 8, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Reference = "TCK-2026-0012",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Closed",
                            Title = "Sample ticket 12"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000013"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 27, 13, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            Reference = "TCK-2026-0013",
                            Status = "New",
                            Title = "Sample ticket 13"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000014"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 27, 13, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            Reference = "TCK-2026-0014",
                            Status = "InProgress",
                            Title = "Sample ticket 14"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000015"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 27, 13, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            Reference = "TCK-2026-0015",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Resolved",
                            Title = "Sample ticket 15"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000016"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            ClosedDate = new DateTime(2026, 8, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 8, 27, 13, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            Reference = "TCK-2026-0016",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Closed",
                            Title = "Sample ticket 16"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000017"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Reference = "TCK-2026-0017",
                            Status = "New",
                            Title = "Sample ticket 17"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000018"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Reference = "TCK-2026-0018",
                            Status = "InProgress",
                            Title = "Sample ticket 18"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000019"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Reference = "TCK-2026-0019",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Resolved",
                            Title = "Sample ticket 19"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000020"),
                            AssignedAgentId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            ClosedDate = new DateTime(2026, 8, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "support@pecb.com",
                            CustomerName = "PECB Customer",
                            Description = "Seeded ticket for demo purposes.",
                            DueDate = new DateTime(2026, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 8, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            Reference = "TCK-2026-0020",
                            ResolvedDate = new DateTime(2026, 8, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Closed",
                            Title = "Sample ticket 20"
                        });
                });

            modelBuilder.Entity("SupportDesk.Core.Entities.Comment", b =>
                {
                    b.HasOne("SupportDesk.Core.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportDesk.Core.Entities.Ticket", b =>
                {
                    b.HasOne("SupportDesk.Core.Entities.Agent", "AssignedAgent")
                        .WithMany("Tickets")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedAgent");
                });

            modelBuilder.Entity("SupportDesk.Core.Entities.Agent", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SupportDesk.Core.Entities.Ticket", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
